# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Translators:
# BluGen, 2014
# Michael Tremer <michael.tremer@ipfire.org>, 2012,2014
# Peter Cloudstone <rmg-mainz@web.de>, 2014
# BlockMall, 2014
msgid ""
msgstr ""
"Project-Id-Version: IPFire Project\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2014-09-29 14:20+0000\n"
"PO-Revision-Date: 2014-09-29 14:26+0000\n"
"Last-Translator: Michael Tremer <michael.tremer@ipfire.org>\n"
"Language-Team: German (http://www.transifex.com/projects/p/ipfire/language/"
"de/)\n"
"Language: de\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: ../src/ddns/__init__.py:63
msgid "Debugging mode enabled"
msgstr "Debugmodus eingeschaltet"

#: ../src/ddns/__init__.py:90
#, python-format
msgid "Loading configuration file %s"
msgstr "Lade Konfigurationsdatei %s"

#: ../src/ddns/__init__.py:156
msgid "Found no entries in the configuration file. Exiting."
msgstr "Keine Einträge in der Konfigurationsdatei gefunden. Ende."

#: ../src/ddns/__init__.py:167
#, python-format
msgid "Dynamic DNS update for %(hostname)s (%(provider)s) failed:"
msgstr "Dynamic DNS-Update für %(hostname)s (%(provider)s) fehlgeschlagen"

#: ../src/ddns/__init__.py:174
#, python-format
msgid ""
"Dynamic DNS update for %(hostname)s (%(provider)s) throwed an unhandled "
"exception:"
msgstr ""
"Dynamic DNS-Update für %(hostname)s (%(provider)s) erzeugte einen "
"unerwarteten Fehler:"

#: ../src/ddns/errors.py:29
msgid "Error"
msgstr "Fehler"

#: ../src/ddns/errors.py:39
msgid "Network error"
msgstr "Netzwerkfehler"

#: ../src/ddns/errors.py:47
msgid ""
"The server denied processing the request because account abuse is suspected"
msgstr ""
"Der Server hat die Anfrage aufgrund eines Missbrauchsverdachts zurückgewiesen"

#: ../src/ddns/errors.py:55
msgid "Authentication against the server has failed"
msgstr "Die Authentifizierung am Server ist fehlgeschlagen"

#: ../src/ddns/errors.py:64
msgid "The server denies any updates from this client"
msgstr "Der Server weist alle Aktualisierungen dieses Clients zurück"

#: ../src/ddns/errors.py:72
msgid "The configuration file has errors"
msgstr "Die Konfigurationsdatei weist Fehler auf"

#: ../src/ddns/errors.py:79
msgid "Connection refused"
msgstr "Verbindung zurückgewiesen"

#: ../src/ddns/errors.py:86 ../src/ddns/system.py:218
msgid "Connection timeout"
msgstr "Verbindungstimeout"

#: ../src/ddns/errors.py:94
msgid "The host could not be found in the configuration file"
msgstr "Der Host konnte in der Konfigurationsdatei nicht gefunden werden"

#: ../src/ddns/errors.py:102
msgid "Internal server error"
msgstr "Interner Serverfehler"

#: ../src/ddns/errors.py:109
msgid "Network unreachable"
msgstr "Netzwerk nicht erreichbar"

#: ../src/ddns/errors.py:116
#, fuzzy
msgid "Not found"
msgstr "Domain nicht gefunden."

#: ../src/ddns/errors.py:124
msgid "Request error"
msgstr "Request-Fehler"

#: ../src/ddns/errors.py:132
msgid "Could not resolve DNS entry"
msgstr ""

#: ../src/ddns/errors.py:139
msgid "Service unavailable"
msgstr "Service nicht verfügbar"

#: ../src/ddns/errors.py:147
msgid "The update could not be performed"
msgstr "Die Aktualisierung konnte nicht ausgeführt werden"

#: ../src/ddns/providers.py:85
msgid "Provider is not properly configured"
msgstr ""

#: ../src/ddns/providers.py:154
#, python-format
msgid "Updating %s forced"
msgstr "Aktualisierung von %s erzwungen"

#: ../src/ddns/providers.py:170
#, python-format
msgid "Dynamic DNS update for %(hostname)s (%(provider)s) successful"
msgstr "Dynamic DNS-Update für %(hostname)s (%(provider)s) erfolgreich"

#: ../src/ddns/providers.py:194
#, fuzzy, python-format
msgid ""
"An update for %(hostname)s (%(provider)s) is performed because of an IP "
"address change"
msgstr ""
"Dynamic DNS-Update für %(hostname)s (%(provider)s) erzeugte einen "
"unerwarteten Fehler:"

#: ../src/ddns/providers.py:202
#, fuzzy, python-format
msgid ""
"An update for %(hostname)s (%(provider)s) is performed because the holdoff "
"time has expired"
msgstr ""
"Dynamic DNS-Update für %(hostname)s (%(provider)s) erzeugte einen "
"unerwarteten Fehler:"

#. Otherwise, we don't need to perform an update
#: ../src/ddns/providers.py:209
#, fuzzy, python-format
msgid "No update required for %(hostname)s (%(provider)s)"
msgstr "Dynamic DNS-Update für %(hostname)s (%(provider)s) fehlgeschlagen"

#: ../src/ddns/providers.py:228 ../src/ddns/providers.py:242
#, python-format
msgid "An update has not been performed because earlier updates failed for %s"
msgstr ""

#: ../src/ddns/providers.py:230
msgid "There will be no retries"
msgstr ""

#: ../src/ddns/providers.py:246
msgid "Last failure message:"
msgstr ""

#: ../src/ddns/providers.py:251
#, python-format
msgid "Further updates will be withheld until %s"
msgstr ""

#: ../src/ddns/providers.py:385 ../src/ddns/providers.py:612
#: ../src/ddns/providers.py:1191 ../src/ddns/providers.py:1340
msgid "No valid FQDN was given."
msgstr "Kein gültiger FQDN angegeben."

#: ../src/ddns/providers.py:387
msgid "Specified host does not exist."
msgstr "Der angebene Host existiert nicht."

#: ../src/ddns/providers.py:391
msgid "DNS error encountered."
msgstr "DNS-Fehler aufgetreten."

#. If we got here, some other update error happened.
#: ../src/ddns/providers.py:396 ../src/ddns/providers.py:785
#, python-format
msgid "Server response: %s"
msgstr "Antwort des Servers: %s"

#: ../src/ddns/providers.py:531
msgid "Scriptlet:"
msgstr ""

#: ../src/ddns/providers.py:614 ../src/ddns/providers.py:661
msgid "Invalid hostname specified."
msgstr "Ungültiger Computername angegeben."

#: ../src/ddns/providers.py:616
msgid "Hostname not marked as a dynamic host."
msgstr "Computername nicht als dynamischer Computer markiert."

#: ../src/ddns/providers.py:618 ../src/ddns/providers.py:670
#: ../src/ddns/providers.py:905
msgid "Invalid IP address has been sent."
msgstr "Ungültige IP-Adresse abgeschickt."

#: ../src/ddns/providers.py:658
msgid "No hostname specified."
msgstr "Kein Hostname angegeben."

#: ../src/ddns/providers.py:667
msgid "Account has been disabled."
msgstr "Der Account wurde deaktiviert."

#: ../src/ddns/providers.py:673
msgid "Too many failed requests."
msgstr "Zu viele fehlgeschlagene Anfragen."

#: ../src/ddns/providers.py:776
#, fuzzy
msgid "Malformed request has been sent."
msgstr "Ungültige IP-Adresse abgeschickt."

#: ../src/ddns/providers.py:780
msgid "Too frequent update requests have been sent."
msgstr ""

#: ../src/ddns/providers.py:826 ../src/ddns/providers.py:1013
msgid "Domain not found."
msgstr "Domain nicht gefunden."

#: ../src/ddns/providers.py:861
#, fuzzy
msgid "An invalid IP address was submitted"
msgstr "Ungültige IP-Adresse abgeschickt."

#: ../src/ddns/providers.py:1015
msgid "Domain not active."
msgstr "Domain nicht aktiv."

#: ../src/ddns/providers.py:1165
msgid "No Auth details specified."
msgstr "Keine Authentifizierungsdetails angegeben."

#: ../src/ddns/providers.py:1187
msgid "Invalid IPv4 address has been sent."
msgstr "Eine ungültige IPv4-Adresse wurde gesendet."

#: ../src/ddns/providers.py:1189
msgid "Invalid IPv6 address has been sent."
msgstr "Eine ungültige IPv6-Adresse wurde gesendet."

#: ../src/ddns/providers.py:1385
#, fuzzy
msgid "Invalid hostname specified"
msgstr "Ungültiger Computername angegeben."

#: ../src/ddns/system.py:55
#, python-format
msgid "Running on distribution: %s"
msgstr "Laufe auf Distribution: %s"

#: ../src/ddns/system.py:153
msgid "Request header:"
msgstr "Request-Header:"

#. Log response header.
#: ../src/ddns/system.py:161 ../src/ddns/system.py:170
#, python-format
msgid "Response header (Status Code %s):"
msgstr "Header der Antwort (Status Code %s):"

#~ msgid "%s is already up to date"
#~ msgstr "%s ist bereits auf dem neuesten Stand"
