# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Translators:
# Ersan YILDIRIM <yakazan@gmail.com>, 2014
# K. Emre, 2014
msgid ""
msgstr ""
"Project-Id-Version: IPFire Project\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2014-09-29 14:20+0000\n"
"PO-Revision-Date: 2014-09-29 14:25+0000\n"
"Last-Translator: Michael Tremer <michael.tremer@ipfire.org>\n"
"Language-Team: Turkish (http://www.transifex.com/projects/p/ipfire/language/"
"tr/)\n"
"Language: tr\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"

#: ../src/ddns/__init__.py:63
msgid "Debugging mode enabled"
msgstr "Hata ayıklama modu etkinleştirildi"

#: ../src/ddns/__init__.py:90
#, python-format
msgid "Loading configuration file %s"
msgstr "%s yapılandırma dosyası yükleniyor"

#: ../src/ddns/__init__.py:156
msgid "Found no entries in the configuration file. Exiting."
msgstr "Yapılandırma dosyasında hiçbir girdi bulunamadı. Çıkılıyor."

#: ../src/ddns/__init__.py:167
#, python-format
msgid "Dynamic DNS update for %(hostname)s (%(provider)s) failed:"
msgstr ""
"%(hostname)s (%(provider)s) için dinamik DNS güncelleştirmesi başarısız oldu."

#: ../src/ddns/__init__.py:174
#, python-format
msgid ""
"Dynamic DNS update for %(hostname)s (%(provider)s) throwed an unhandled "
"exception:"
msgstr ""
"%(hostname)s (%(provider)s) dinamik DNS işlenmesinde özel bir durum oluştu:"

#: ../src/ddns/errors.py:29
msgid "Error"
msgstr "Hata"

#: ../src/ddns/errors.py:39
msgid "Network error"
msgstr "Ağ hatası"

#: ../src/ddns/errors.py:47
msgid ""
"The server denied processing the request because account abuse is suspected"
msgstr ""
"Sunucu isteği işlemeyi reddetti çünkü hesabı kötüye kullanma şüphesi var."

#: ../src/ddns/errors.py:55
msgid "Authentication against the server has failed"
msgstr "Sunucuyla kimlik doğrulama başarısız oldu."

#: ../src/ddns/errors.py:64
msgid "The server denies any updates from this client"
msgstr "Sunucu bu istemciden güncellemeye izin vermiyor."

#: ../src/ddns/errors.py:72
msgid "The configuration file has errors"
msgstr "Yapılandırma dosyasında hatalar var."

#: ../src/ddns/errors.py:79
msgid "Connection refused"
msgstr "Bağlantı reddedildi"

#: ../src/ddns/errors.py:86 ../src/ddns/system.py:218
msgid "Connection timeout"
msgstr "Bağlantı zaman aşımına uğradı"

#: ../src/ddns/errors.py:94
msgid "The host could not be found in the configuration file"
msgstr "Ana bilgisayar yapılandırma dosyasında bulunamadı."

#: ../src/ddns/errors.py:102
msgid "Internal server error"
msgstr "İç sunucu hatası"

#: ../src/ddns/errors.py:109
msgid "Network unreachable"
msgstr "Ağa ulaşılamıyor"

#: ../src/ddns/errors.py:116
#, fuzzy
msgid "Not found"
msgstr "Etki alanı bulunamadı."

#: ../src/ddns/errors.py:124
msgid "Request error"
msgstr "İstek hatası"

#: ../src/ddns/errors.py:132
msgid "Could not resolve DNS entry"
msgstr ""

#: ../src/ddns/errors.py:139
msgid "Service unavailable"
msgstr "Hizmet kullanılamıyor"

#: ../src/ddns/errors.py:147
msgid "The update could not be performed"
msgstr "Güncelleme yapılamadı"

#: ../src/ddns/providers.py:85
msgid "Provider is not properly configured"
msgstr ""

#: ../src/ddns/providers.py:154
#, python-format
msgid "Updating %s forced"
msgstr "%s güncellemeye zorlandı"

#: ../src/ddns/providers.py:170
#, python-format
msgid "Dynamic DNS update for %(hostname)s (%(provider)s) successful"
msgstr ""
"%(hostname)s (%(provider)s) için dinamik DNS güncellemesi başarıyla yapıldı "

#: ../src/ddns/providers.py:194
#, fuzzy, python-format
msgid ""
"An update for %(hostname)s (%(provider)s) is performed because of an IP "
"address change"
msgstr ""
"%(hostname)s (%(provider)s) dinamik DNS işlenmesinde özel bir durum oluştu:"

#: ../src/ddns/providers.py:202
#, fuzzy, python-format
msgid ""
"An update for %(hostname)s (%(provider)s) is performed because the holdoff "
"time has expired"
msgstr ""
"%(hostname)s (%(provider)s) dinamik DNS işlenmesinde özel bir durum oluştu:"

#. Otherwise, we don't need to perform an update
#: ../src/ddns/providers.py:209
#, fuzzy, python-format
msgid "No update required for %(hostname)s (%(provider)s)"
msgstr ""
"%(hostname)s (%(provider)s) için dinamik DNS güncelleştirmesi başarısız oldu."

#: ../src/ddns/providers.py:228 ../src/ddns/providers.py:242
#, python-format
msgid "An update has not been performed because earlier updates failed for %s"
msgstr ""

#: ../src/ddns/providers.py:230
msgid "There will be no retries"
msgstr ""

#: ../src/ddns/providers.py:246
msgid "Last failure message:"
msgstr ""

#: ../src/ddns/providers.py:251
#, python-format
msgid "Further updates will be withheld until %s"
msgstr ""

#: ../src/ddns/providers.py:385 ../src/ddns/providers.py:612
#: ../src/ddns/providers.py:1191 ../src/ddns/providers.py:1340
msgid "No valid FQDN was given."
msgstr "Geçerli FQDN verilmedi."

#: ../src/ddns/providers.py:387
msgid "Specified host does not exist."
msgstr "Belirtilen ana bilgisayar yok."

#: ../src/ddns/providers.py:391
msgid "DNS error encountered."
msgstr "DNS hatası ile karşılaşıldı."

#. If we got here, some other update error happened.
#: ../src/ddns/providers.py:396 ../src/ddns/providers.py:785
#, python-format
msgid "Server response: %s"
msgstr "Sunucu yanıtı: %s"

#: ../src/ddns/providers.py:531
msgid "Scriptlet:"
msgstr ""

#: ../src/ddns/providers.py:614 ../src/ddns/providers.py:661
msgid "Invalid hostname specified."
msgstr "Geçersiz ana bilgisayar adı belirtildi."

#: ../src/ddns/providers.py:616
msgid "Hostname not marked as a dynamic host."
msgstr "Ana bilgisayar adı, dinamik ana bilgisayar olarak işaretli değil."

#: ../src/ddns/providers.py:618 ../src/ddns/providers.py:670
#: ../src/ddns/providers.py:905
msgid "Invalid IP address has been sent."
msgstr "Geçersiz IP adresi gönderildi."

#: ../src/ddns/providers.py:658
msgid "No hostname specified."
msgstr "Ana bilgisayar adı belirtilmedi."

#: ../src/ddns/providers.py:667
msgid "Account has been disabled."
msgstr "Hesap devre dışı bırakıldı."

#: ../src/ddns/providers.py:673
msgid "Too many failed requests."
msgstr "Çok fazla başarısız istek."

#: ../src/ddns/providers.py:776
#, fuzzy
msgid "Malformed request has been sent."
msgstr "Geçersiz IP adresi gönderildi."

#: ../src/ddns/providers.py:780
msgid "Too frequent update requests have been sent."
msgstr ""

#: ../src/ddns/providers.py:826 ../src/ddns/providers.py:1013
msgid "Domain not found."
msgstr "Etki alanı bulunamadı."

#: ../src/ddns/providers.py:861
#, fuzzy
msgid "An invalid IP address was submitted"
msgstr "Geçersiz IP adresi gönderildi."

#: ../src/ddns/providers.py:1015
msgid "Domain not active."
msgstr "Etki alanı aktif değil."

#: ../src/ddns/providers.py:1165
msgid "No Auth details specified."
msgstr "Kimlik doğrulama detayları belirtilmedi."

#: ../src/ddns/providers.py:1187
msgid "Invalid IPv4 address has been sent."
msgstr "Geçersiz IPv4 adresi gönderildi."

#: ../src/ddns/providers.py:1189
msgid "Invalid IPv6 address has been sent."
msgstr "Geçersiz IPv6 adresi gönderildi."

#: ../src/ddns/providers.py:1385
#, fuzzy
msgid "Invalid hostname specified"
msgstr "Geçersiz ana bilgisayar adı belirtildi."

#: ../src/ddns/system.py:55
#, python-format
msgid "Running on distribution: %s"
msgstr "Üzerinde çalışılan dağıtım: %s"

#: ../src/ddns/system.py:153
msgid "Request header:"
msgstr "İstek başlığı:"

#. Log response header.
#: ../src/ddns/system.py:161 ../src/ddns/system.py:170
#, python-format
msgid "Response header (Status Code %s):"
msgstr "Yanıt başlığı (Durum Kodu %s)"
